/*
 * This source file was generated by the Gradle 'init' task
 */
package org.team7525;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertNotNull(GreetLibrary.greet("Bogdan"), "app should have a greeting");
    }
}
